### ISSUE TITLE
Cannot open piano roll after initial run (sample video)

### ISSUE THREAD

**Issue by EverTokki** [nai-kon/PlaySK-Piano-Roll-Reader#11]
I keep getting the error "Error: Player Setting File Load Failed". This problem seems to occur _after_ I've opened the program once and played with it, and then happens for all options available. It's either the error pops up or the program crashes.

Also, just a question.. How would you use this as a MIDI input to a program? You mentioned it outputs MIDI, and I would like to record that on a software - is it possible?

Thank you.

**Comment by nai-kon** [comment]
Hello. Sorry for the late reply.
It seems the setting file is not found on the original directory. 
Did you change the location of files? The files should be located like below image.
![image](https://user-images.githubusercontent.com/25865392/223989507-119ada75-a80e-4b8a-bbe9-f645e20e4a3b.png)

> I would like to record that on a software - is it possible?

Yes, it is possible with "loopMIDI" software. 
[This software] -> [loopMIDI virtual port] -> [Recording software]
