### ISSUE TITLE
example_scans source question

### ISSUE THREAD

**Issue by luctrott** [nai-kon/PlaySK-Piano-Roll-Reader#13]
I'm wondering where I can get/download the images of Terry Smith's scanned rolls from, I want to experiment a bit but I can only find the .mid file, but not the "image" archive.

**Comment by nai-kon** [comment]
You can download it from this post.
https://www.mmdigest.com/Archives/Digests/201701/2017.01.24.02.html

notes: PlaySK software only supports general image format such as jpg or png, bmp. 
So .cis files need conversion. I'm using Anthony Robinson's software to convert cis -> tiff.
http://semitone440.co.uk/rolls/utils/

Then cut off the roll margin on both edges like sample scans and convert to .png.

I’m considering support .cis format without any hassle conversion.

**Comment by luctrott** [comment]
Thank you very much for the quick and detailed answer. Unfortunately, it seems that the archive on Google Drive is access-restricted and my request has not yet been confirmed.
Do you know if anyone is still taking care of it, or do you have another source where I can get the data?
Thank you

**Comment by nai-kon** [comment]
>I’m considering support .cis format without any hassle conversion.

I supported direct load .cis files on latest release. Please download and try this.
https://github.com/nai-kon/PlaySK-Piano-Roll-Reader/releases/tag/Ver3.1

I added more sample scans. If you need more, please let me your e-mail address. I will send you.

**Comment by nai-kon** [comment]
@luctrott 
How are you. Can I close this issue?

**Comment by luctrott** [comment]
Sorry, here is my mail address: luctrott@gmail.com
If possible, it would be nice if you could send me all CIS files you have. I have found some issues/wierd parts in the midi archive and would like to have a look at the corresponding scans. (Also, I love to watch the rolls as they are played and am working on a roll scanner myself which will be based on a raspberry with camera,  for which I would like to have a huge dataset of test data).

**Comment by nai-kon** [comment]
@luctrott 
I sent an email on October 26th. Please check it.

**Comment by luctrott** [comment]
Thank you very much!
