### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by asdf91918** [nai-kon/PlaySK-Piano-Roll-Reader#9]
Sk player does not output audio to piano vst in FL studio

**Comment by nai-kon** [comment]
I'm using an Ivory2 piano vst via "loopMidi", the virtual midi cable.

Maybe you need to install "loopMidi".
1. At FL studio, set midi input port to "loopMidi"
2. At this software, set midi output port to "loopMidi"

**Comment by nai-kon** [comment]
@asdf91918 
Can we close this issue?
